esphome:
  name: mipurifier
  comment: for Xiaomi Mi Air Purifier 3H (and similar models using the same protocol)
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true

external_components:
  
  - source:
      type: local
      path: ./components
    components: [ mipurifier ]

# Enable logging
logger:

ota:
  password:  !secret ota_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback"
    password:  !secret fallback_password

# captive_portal:

# web_server:
#   port: 80

substitutions:
  devicename: "mipurifier"
  snake_devicename: "mipurifier"
  upper_devicename: "Mipurifier"

text_sensor:
  - platform: version
    name: "${devicename} - Version"
    icon: mdi:cube-outline


#######################################
# Device specific Config Begins Below #
#######################################

# Required configuration for the weird single core ESP-WROOM-32D module



# Initialize the serial connection to the STM32 microcontroller
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

sensor:
  - platform: wifi_signal
    name: ${devicename} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${devicename} Uptime
  - platform: mipurifier
    pm_2_5:
      name: "${devicename} PM2.5 Value"
    temperature:
      name: "${devicename} Temperature Value"
    humidity:
      name: "${devicename} Humidity Value"

switch:
  - platform: mipurifier
    name: "${devicename} Power"
    role: power
  - platform: mipurifier
    name: "${devicename} Beeper"
    role: beeper
  - platform: mipurifier
    name: "${devicename} Child lock"
    role: lock

select:
  - platform: mipurifier
    name: "${devicename} Mode"
    role: mode
  - platform: mipurifier
    name: "${devicename} Screen brightness"
    role: screen_brightness

# Initialize our custom component
mipurifier:
    id: my_mipurifier

